[build]
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/recipe/*"
  to = "apps/recipe-ui/browser/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "apps/blog-ui/browser/index.html"
  status = 200