[build]
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/recipe/*"
  to = "/recipe/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/blog/index.html"
  status = 200
