[build]
  command = "npm install && npm run build"
  publish = "dist/apps"

[[redirects]]
  # Redirect for recipe app
  from = "/recipe/*"
  to = "/recipe-ui/browser/index.html"
  status = 200

[[redirects]]
  # Redirect for blog app
  from = "/blog/*"
  to = "/blog-ui/browser/index.html"
  status = 200

[[headers]]
  # Set headers for JavaScript and CSS files
  for = "/*"
  [headers.values]
    Content-Type = "application/javascript"
    Content-Type = "text/css"

[[headers]]
  # Cache static assets for recipe-ui
  for = "/recipe-ui/browser/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache static assets for blog-ui
  for = "/blog-ui/browser/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
