[build]
  command = "npm install && npm run build"
  publish = "dist/apps"

[[redirects]]
  # Redirect for recipe app
  from = "/recipe/*"
  to = "/recipe-ui/browser/index.html"
  status = 200
  force = false

[[redirects]]
  # Redirect for blog app
  from = "/blog/*"
  to = "/blog-ui/browser/index.html"
  status = 200
  force = false

[[redirects]]
  # Prevent static assets from being redirected
  from = "/*"
  to = "/"
  status = 200
  query = "!js,!css,!map,!png,!jpg,!jpeg,!gif,!svg"

[[headers]]
  # Set Content-Type for JavaScript files
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  # Set Content-Type for CSS files
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  # Cache static assets for recipe-ui
  for = "/recipe-ui/browser/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache static assets for blog-ui
  for = "/blog-ui/browser/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
